import { Web3sdkioSDK } from "../sdk";
import { Network } from "../types/index";
import { getPayer } from "./local-config";
import { KeypairSigner } from "@metaplex-foundation/js";
import { Web3sdkioStorage } from "@web3sdkio/storage";

/**
 * Create an SDK instance using the local configuration generated by the Solana CLI
 *
 * @example
 * ```jsx
 * import { createWeb3sdkioSDK } from "@web3sdkio/sdk/solana";
 *
 * // Select the network to create the SDK on
 * const sdk = createWeb3sdkioSDK("devnet");
 * ```
 *
 * @public
 */
export function createWeb3sdkioSDK(
  network: Network,
  storage: Web3sdkioStorage = new Web3sdkioStorage(),
): Web3sdkioSDK {
  const payer = getPayer();
  const signer: KeypairSigner = {
    publicKey: payer.publicKey,
    secretKey: payer.secretKey,
  };
  const sdk = Web3sdkioSDK.fromNetwork(network, storage);
  sdk.wallet.connect(signer);
  return sdk;
}
